### ISSUE TITLE
Error: Cannot find module 'yaml'

### ISSUE THREAD

**Issue by Philamericus** [Mermade/widdershins#259]
Hi. I have been using Widdershins for a while with great results :)
Today, I updated all source files from GitHub, and now when I run it, I get this error:

````
$ node widdershins.js --summary -search true ./defs/crypto-2.0.1907.yaml --language_tabs 'javascript:JavaScript' 'shell:Shell' -o crypto.md
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yaml'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\phil.americus\Documents\GitHub\shins\widdershins\widdershins.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
````
I am running it on Windows, using cygwin.

Do you have any idea what the problem is?

**Comment by MikeRalphson** [comment]
Will check the package.json / package-lock.json files...

**Comment by MikeRalphson** [comment]
Oh, you may need to `npm i` again if you haven't done so.

**Comment by Philamericus** [comment]
Hey, that fixed it! Thanks for the quick response!

**Comment by MikeRalphson** [comment]
No problem.
