### ISSUE TITLE
TypeError using widdershins@3.0.0-beta0.1

### ISSUE THREAD

**Issue by stiancognite** [Mermade/widdershins#69]
Hey Mike, is there something wrong with my `openapi.json` file here?
[openapi.json.zip](https://github.com/Mermade/widdershins/files/1491453/openapi.json.zip)

```
➜  api git:(swagger2) ✗ widdershins --version
3.0.0-beta0.1
➜  api git:(swagger2) ✗ widdershins -x swagger/openapi.json --maxDepth 5 -o index.html.md
Compiling all doT templates...
Loaded def authentication.def
Loaded def authentication_none.def
Loaded def callbacks.def
Loaded def debug.def
Loaded def discovery.def
Loaded def footer.def
Loaded def links.def
Loaded def parameters.def
Loaded def responses.def
Loaded def security.def
Compiling code_http.dot to function
Compiling code_java.dot to function
Compiling code_javascript.dot to function
Compiling code_nodejs.dot to function
Compiling code_python.dot to function
Compiling code_ruby.dot to function
Compiling code_shell.dot to function
Compiling main.dot to function
Compiling operation.dot to function
Compiling translations.dot to function
TypeError: Cannot read property 'trim' of undefined
    at Object.getResponses (/usr/local/lib/node_modules/widdershins/openapix.js:324:46)
    at Object.eval [as operation] (eval at doT.template (/usr/local/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:2566)
    at Object.eval [as main] (eval at doT.template (/usr/local/lib/node_modules/widdershins/node_modules/dot/doT.js:133:11), <anonymous>:3:3445)
    at convertInner (/usr/local/lib/node_modules/widdershins/openapix.js:536:30)
    at Object.convert (/usr/local/lib/node_modules/widdershins/openapix.js:557:9)
    at Object.convert (/usr/local/lib/node_modules/widdershins/index.js:22:22)
    at doit (/usr/local/lib/node_modules/widdershins/widdershins.js:86:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/widdershins/widdershins.js:144:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

**Comment by MikeRalphson** [comment]
Response Object descriptions are mandatory (though they can be blank) - that said, it shouldn't crash `widdershins`! Fix in widdershins@3.0.0-beta0.2

Thanks for testing, and for letting me know.
